# Generated by Django 5.0.6 on 2024-10-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('imagem', models.ImageField(upload_to='')),
                ('nome', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.TextField()),
                ('endereco', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
