# Generated by Django 5.1.2 on 2024-10-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imovel', '0003_alter_imovel_imagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(default='Endereço não informado', max_length=255),
        ),
    ]
