# Generated by Django 5.1.2 on 2024-10-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imovel', '0004_alter_imovel_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(max_length=250),
        ),
    ]
