# Generated by Django 5.1.2 on 2024-10-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imovel', '0005_alter_imovel_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(default='Descrição não fornecida'),
        ),
    ]
