# Generated by Django 5.1.2 on 2024-10-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Imovel', '0006_alter_imovel_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='endereco',
        ),
    ]
