# Generated by Django 5.1.2 on 2024-10-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imovel', '0008_remove_imovel_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(default='Descrição não fornecida'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(default='Endereço não informado', max_length=255),
        ),
    ]
